paul999_downloadpage_main:
    pattern: /downloads
    defaults: { _controller: paul999.downloadpage.controller:main }

paul999_downloadpage_download:
    pattern: /downloads/{id}/{name}.zip
    defaults: { _controller: paul999.downloadpage.controller:download }